### ISSUE TITLE
Feature Request: Flag key alias support

### ISSUE THREAD

**Issue by matthalbersma** [launchdarkly/ld-find-code-refs#104]
In most of our use cases the flag reference string is made into a constant. Find Code Refs only surfaces the exact string. This doesn't really do much good when we're looking for actual invocations of the ldclient. I realize walking the code for variable reference is not easy, but would be an interesting feature going forward.

**Comment by brandon-sling** [comment]
I've been going back and forth over whether or not to make this request. Right now it's not too important to the teams that use LD to know where the flag is used, compared to whether it is used, since they have other tools for analyzing the code. Going forward for new teams that might use LD, this could be helpful.

**Comment by atrakh** [comment]
Hi, thanks for submitting this request. This suggestion would be a meaningful enhancement for LaunchDarkly users that don't directly reference flag keys in their flag evaluations.

We've thought about adding similar support, but ultimately decided to build a simple search implementation of reference scanning to better support the sprawling number of programming languages LaunchDarkly provides SDKs for.

At the time, we don't have any immediate plans to build this. To help us understand where this functionality would be most useful, can you tell me which language(s) you'd want this kind of support for?

As an aside, a common pattern we've noticed is feature flag keys being stored in constants with similar names with alternative casings (e.g. `myFlagKey := "my-flag-key"`). In fact, our React SDK camel-cases feature flag keys [by default](https://docs.launchdarkly.com/sdk/client-side/react#configuring-the-react-sdk). Would an option to have the `ld-find-code-refs` scan for multiple casings of a flag key suffice for your usage of LaunchDarkly?

**Comment by brandon-sling** [comment]
Commonly I see an all-caps with underscore approach e.g. `MY_FLAG_KEY = "my-flag-key"`

**Comment by atrakh** [comment]
This is long overdue, but we've just launched a beta version of `ld-find-code-references` with supported. 

To use this release, update your version of coderefs to `1.5.0-beta1` (the `latest` tag will not work). If you're using the CircleCI Orb, the tag is `dev:1.5.0-beta1`.

You can configure patterns for generating aliases using a YAML file. Documentation for configuration can be found here: https://github.com/launchdarkly/ld-find-code-refs#configuring-aliases.

@brandon-sling For your specific example, you would be able to use the `upperSnakeCase` configuration type, or set up a [file pattern](https://github.com/launchdarkly/ld-find-code-refs#search-a-file-for-a-specific-pattern) with a regular expression.

One thing to note is that aliases don't currently support the existing `delimeters` option available to regular flag keys. We might add that as a configurable option later if it appears to be necessary.

We're supporting this release as of now, but we'll keep it in beta (and this issue open for feedback) until we finalize what the configuration will look like.

**Comment by atrakh** [comment]
Hi all, version 1.5.0 is now out of beta, so "aliases" are now officially released.

 I'm going to close this issue now, but please feel free to leave additional comments or open a new issue should any questions or feedback come up.

Thanks,
Arnold
