### ISSUE TITLE
Gitlab CI suggestion

### ISSUE THREAD

**Issue by matthalbersma** [launchdarkly/ld-find-code-refs#105]
The process explained in your [docs](https://github.com/launchdarkly/LaunchDarkly-Docs/blob/master/src/content/topics/integrations/git-code-references/gitlab-ci.mdx)  can be simplified by using your pre-generated docker image. 

My CI looks something like.

```
find_ld_code_refs:
    stage: build
    image: 
      name: launchdarkly/ld-find-code-refs:1.3.1
      entrypoint: [""]
    script:
      - ld-find-code-refs 
         -projKey=$LD_PROJECT
         -dir=$CI_PROJECT_DIR
         -accessToken=$LAUNCH_DARKLY_TOKEN
         -repoName=$CI_PROJECT_NAME
         -branch=$CI_COMMIT_BRANCH
    only:
      refs:
        - master
```

**Comment by atrakh** [comment]
Hi @matthalbersma,

Thank you for the suggestion. I've tested this out and it looks good :)

You can track the status of this change in this reference PR above this comment.
