### ISSUE TITLE
parse yaml file

### ISSUE THREAD

**Issue by sgandon** [launchdarkly/ld-find-code-refs#115]
Hello,
I have added the flag key in a yaml file like this 
```
key:
  flag: arch-291-segment-unit-test
```
And it does not get found.
There are some delimiter set to "`' which seems to be used and thus making this flag unseen.
I there a way to have this flag found ?  
I have added " around the flag and it gets found but is there a configuration parameter (I am using github action) to have the above fine parse correctly ?
thanks.

**Comment by atrakh** [comment]
Hi @sgandon,

Thanks for writing in. If I understand correctly, you're project is storing feature flag keys in a YAML file, and you'd like to be able to have `ld-find-code-refs` detect those keys.

At this time, basic `ld-find-code-refs` search does not allow for disabling the default delimiters. I I can see how being able to do so would be a reasonable enhancement - this would be a great addition for the next version of the tool.

### Workaround (new feature)
You may be interested in the new [aliases](https://github.com/launchdarkly/ld-find-code-refs#configuring-aliases) feature we're supporting as a beta. Aliases can be used to search for "references of references", such as constant variables storing flag keys. With a bit of clever configuration, aliases can be used to search for flag keys themselves without delimiters.

If you'd like to try out aliases, you will need to upgrade to the latest beta version of the tool (currently 1.5.0-beta2). For github actions, you can set the version like so:
```yaml
uses: launchdarkly/find-code-references@1.5.0-beta2
```

Aliases use a YAML configuration format to define search. This YAML file should be stored in your repository as `.launchdarkly/coderefs.yaml`.

Assuming all of your flag keys follow the default dash-separated format used by LaunchDarkly, this configuration would work to find references:
```yaml
aliases:
  - type: kebabCase
```

To learn more about aliases and what you can do with them, check out the documentation: https://github.com/launchdarkly/ld-find-code-refs#configuring-aliases

Looking forward to your feedback!

Cheers,
Arnold

**Comment by sgandon** [comment]
Thanks a lot for your detailed answer.
I did test the alias workaround you proposed and it worked like a charm.
One side note, I did try it with the command line installed with brew and although I installed the beta-2 the command line version flag give beta-1
```
ld-find-code-refs -version
ld-find-code-refs version 1.5.0-beta1
```

**Comment by atrakh** [comment]
Glad to hear that this worked out! I'm going to leave this issue open until we have first-class support for disabling delimiters.

Good catch on the version number, looks like I forgot to update a constant 😅

**Comment by atrakh** [comment]
2.0.0 adds support for disabling the default delmiters using the YAML configuration file

https://github.com/launchdarkly/ld-find-code-refs/releases/tag/2.0.0
https://github.com/launchdarkly/ld-find-code-refs/blob/master/docs/CONFIGURATION.md#delimiters
