### ISSUE TITLE
API rate limit

### ISSUE THREAD

**Issue by cuzzasoft** [launchdarkly/ld-find-code-refs#135]
Hey,

Not sure if this is the right place for this - lately our builds are getting rate limited when trying to update code refs:

```
+ docker run --rm -v /buildeng/bamboo-agent-home/xml-data/build-dir/MASTERGENERAL-LDCODEREFS-SCAN/yeet:/repo launchdarkly/ld-find-code-refs:1.3.1 -accessToken=******** -projKey=yeet -repoName=yeet -dir=/repo -contextLines=-1 -debug=true -branch master
Unable to find image 'launchdarkly/ld-find-code-refs:1.3.1' locally
1.3.1: Pulling from launchdarkly/ld-find-code-refs
...
Digest: sha256:a95e29e448e6dd3a1bff9ea90e872358af50c00e6509dfc8df05eb7f28e64443
Status: Downloaded newer image for launchdarkly/ld-find-code-refs:1.3.1
FATAL Please file an issue at https://github.com/launchdarkly/ld-find-code-refs: 2020/09/28 04:19:42 coderefs.go:100: error updating repository: rate_limited, You've exceeded the API rate limit. Try again later.
```

Apparently https://apidocs.launchdarkly.com/reference#rate-limiting seems to indicate the SDKs aren't rate limited, however I wasn't sure if that was because we're pinned to an older version or if this tool doesn't fall under the umbrella of 'SDK'.

Have y'all got any idea what this may be / if we can fix it? I can try bumping to 1.5.1 since it appears to be latest pre-breaking changes but wanted to check with you first

Cheers :)

**Comment by atrakh** [comment]
Hi @cuzzasoft, thanks for reporting this.

The coderefs tool uses our REST API under the hood, so rate limits do apply. I just updated our rate limit configuration for routes related to coderefs to be a bit more permissive, which should alleviate the error you're seeing. No action is required on your end.

Upgrading to a newer version is not required, but I'd always advocate for using a newer version 😄. Version 1.4.0 adds a new config option, `--ignoreServiceErrors`, which will configure the tool to not fail your build (but still log an error) in situation where the LD API is unreachable or rate limited, if you'd prefer that behavior.

Going to close this one out for now, but please don't hesitate to reply again or open a new issue if you have any questions.
