### ISSUE TITLE
Feature: support recursive globbing when finding aliases

### ISSUE THREAD

**Issue by RookieRick** [launchdarkly/ld-find-code-refs#151]
attn: @InTheCloudDan 
I'm working on integrating this as part of my "hackweek" project; I ran into an issue because in many cases we have "constants" defined like `SOME_FLAG = 'some-flag-key'` and there isn't a prescribed naming convention to put them all in a `constants.py` file or the like, so I need to be able to search an entire project to find these references. `filepath` doesn't support `**` globstar natively but `filepathx` does.
I forked and found that (so far at least) this approach seems to be working: https://github.com/RookieRick/ld-find-code-refs/pull/1 with caveat that it can take a looong time. In my test this morning it took 8 minutes to run on one of our larger repos, but I can live with that (or try to optimize it later) if I'm plugging this in as a "post-build" task in Jenkins.
If you think this would be more broadly useful, happy to do pull request back to the main upstream repo.

**Comment by InTheCloudDan** [comment]
@RookieRick thanks for raising this. I'll look to get a feature request created to track it. I think we may want to take a look at this as part of fixing `**` for `.ldignore` also and I'd lean towards a library such as: https://github.com/bmatcuk/doublestar which looks like it has some performance tests run.

**Comment by RookieRick** [comment]
Sounds good, thanks! Time permitting I may try out some performance tests as well; if so will be sure to share here!
