### ISSUE TITLE
Code references feature in huge monolith repo

### ISSUE THREAD

**Issue by armandorod2000** [launchdarkly/ld-find-code-refs#154]
Hi.

Is there a way to specify which folder in the repo should be scan for code refs? I'm trying to implement this feature in a huge monolith repo using Github actions. The problem is the GHA is taking around an hour to finish the task since there are many sub-folders (maintained by different teams) and I guess it's scanning all of them.

As I understood in the documentation, one can use the file .ldignore to exclude files but this seems not to fit since we want every team owning a sub-folder in the repo to orchestrate the feature to scan only that particular folder.

Is this supported? any hint or workaround?

**Comment by InTheCloudDan** [comment]
Thanks for filing this @armandorod2000 we are exploring adding additional monorepo support for Code References, but as of now there is no easy configuration for scanning only a single subdirectory with the Github Action. You can run it with multiple LD Projects by manually specifying the `repoName` https://github.com/launchdarkly/find-code-references/releases/tag/v11 but it will scan all directories that are not included in `.ldignore`. I'm going to add this to an internal Feature Request we're using to track this support.
