### ISSUE TITLE
Looks like there two 2.3.0 release tags

### ISSUE THREAD

**Issue by chenrui333** [launchdarkly/ld-find-code-refs#172]
👋  it looks like there are two tagged releases (2.3.0 and v2.3.0). Another thing worth calling out is the latest tagged release is not marked with `latest release`. Thanks!

![image](https://user-images.githubusercontent.com/1580956/140621907-0a887362-b3ca-4242-a3d4-a2cce701f7f4.png)

**Comment by InTheCloudDan** [comment]
Hi @chenrui333 we're in progress with making changes to our release process now. I just cleaned up those tags temporarily and we should officially be releasing a new version in the near future. Thanks for letting us know about them!
