### ISSUE TITLE
Any example of demoing the flow of using `extinctions`

### ISSUE THREAD

**Issue by chenrui333** [launchdarkly/ld-find-code-refs#241]
I have just did a simple integration with most my repos, it looks like below:
```
      - name: Scan flags
        run: |
          ld-find-code-refs \
            --accessToken=${LD_ACCESS_TOKEN} \
            --projKey=default \
            --repoName=${REPO} \
            --dir="."
```

I got asked with this warning message in the action run `WARNING: 2022/04/14 18:41:33 coderefs.go:189: unable to generate flag extinctions: object not found`

How I can update the action workflow to improve the `ld-find-code-refs` usage, thanks!

**Comment by carmenquan** [comment]
Hi @chenrui333, thank you for reaching out. The error that you're seeing is being returned from `git-go` https://github.com/go-git/go-git/blob/master/plumbing/object.go#L10 and could indicate an issue with the repository you're running code refs on. I'm happy to investigate more if you can provide more details, or a link to the repo that you're working with.

**Comment by chenrui333** [comment]
I wonder if that is more related to the git HEAD checkout. I will share more info via a support ticket. Thanks!

**Comment by chenrui333** [comment]
The issue is resolved after setting up 

```
      - uses: actions/checkout@v3
        with:
          fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references. Read more: https://github.com/launchdarkly/ld-find-code-refs#searching-for-unused-flags-extinctions
```
