### ISSUE TITLE
ld-find-code-refs missed reporting some flags

### ISSUE THREAD

**Issue by chenrui333** [launchdarkly/ld-find-code-refs#282]
👋  I have set up the pipeline to automate the flag reporting, but found out recently that the code references did not get reported correctly (i.e., it got missed out in the scanning process). 

I am trying to run the command in the default setup in my local, but got the same issue in [here](https://github.com/launchdarkly/ld-find-code-refs/issues/140). When I turned off loopback, I still did not see the code references reported into the LD side.

**Comment by jazanne** [comment]
I'm sorry that you're experiencing this issue.

Can you share which version and platform of the tool you're running as well as output from running with and without `lookback` enabled?

**Comment by chenrui333** [comment]
tool version: 2.7.0
os: macOS

**Comment by jazanne** [comment]
Thank you. Would you be able to share some of the output of the error when you are running code refs?

**Comment by chenrui333** [comment]
I think I have attached it to the emails I sent. (are you able to get that)

**Comment by chenrui333** [comment]
@jazanne can you also tag my name next time when you do the reply?

**Comment by jazanne** [comment]
@chenrui333 thank you I received the logs. Will follow-up with you on your emails.

**Comment by chenrui333** [comment]
This is still an issue when loopback with a large value.
