### ISSUE TITLE
orb not able to read parameters from bash_env

### ISSUE THREAD

**Issue by brondum** [launchdarkly/ld-find-code-refs#311]
We would like not to store our `LD_ACCESS_TOKEN` in our context or in the repo it self. Instead we pull this from our secret store and populate it to `$BASH_ENV` as a `pre_step`.   Currently the orb is running in `sh` instead of `bash` which means that CircleCI doesnt load bash_env automatically. 

Solutions: 
1. Could be to change shell to bash
2. source `$BASH_ENV` before the command

CircleCI docs explaining the use of env-vars and paramenters.
https://circleci.com/docs/env-vars/#parameters-and-bash-environment

> The $BASH_ENV workaround only works with bash, and has not been confirmed to work with other shells.

**Comment by jazanne** [comment]
@brondum thank you for submitting this issue. We will have the team review the proposed change and get back to you.

**Comment by jazanne** [comment]
@brondum thank you for your contribution fixing this issue. It is now available in [orb version 2.9.0](https://circleci.com/developer/orbs/orb/launchdarkly/ld-find-code-refs)
