### ISSUE TITLE
error parsing current commit sha: repository does not exist

### ISSUE THREAD

**Issue by dc185334** [launchdarkly/ld-find-code-refs#313]
Since has issue with GH action I did try to run it from CLI locally. MacOS.

`ld-find-code-refs -t api-*-*-*-*-* --dir /Users/DC185334/repos/office/apps/office/src/ -p XXX --branch develop --repoName office --repoUrl https://github.com/my-org/office
`

ERROR: 2023/01/10 13:46:09 coderefs.go:37: error parsing current commit sha: repository does not exist

So, since repo does not exist I did change dir to parent folder:
`ld-find-code-refs -t api-166bdf29-f11f-456c-8f4a-ec5155c65d84 --dir /Users/DC185334/WORK/office -p XXX --branch develop --repoName office --repoUrl https://github.com/my-org/office`

Now error is:
`ERROR: 2023/01/10 13:51:23 helpers.go:39: error creating repository: LaunchDarkly API responded with status code 403
 Add the --ignoreServiceErrors flag to ignore this error`

**Comment by jazanne** [comment]
@dc185334 this appears to be an issue with the token roles. Please make sure the token has these code references roles https://docs.launchdarkly.com/home/members/role-actions/?q=using+act#code-reference-actions
