### ISSUE TITLE
Error: can't open < parameters.allow_tags >

### ISSUE THREAD

**Issue by kaarla** [launchdarkly/ld-find-code-refs#327]
I'm receiving this error using the last release:

```
/bin/sh: can't open < parameters.allow_tags >>: no such file

Exited with code exit status 1
CircleCI received exit code 1
```

Found that in the source, the call has a typo in the quotation:
https://github.com/launchdarkly/ld-find-code-refs/blob/074df4595eafaa1adcb43f19e2d63b8f48c1c4a2/build/package/circleci/orb.yml#L131

**Comment by jazanne** [comment]
@kaarla thank you for submitting this issue, we are working on a fix.
