### ISSUE TITLE
Tool wont find flags without any delimiters

### ISSUE THREAD

**Issue by kostyay** [launchdarkly/ld-find-code-refs#376]
Hi
Id like the tool to search yaml files and find the following occurences:
```yaml
my_logic:
    featureFlag: flag-name
```

As you can see its not quoted.
How can I configure the tool to find such references?
It's not delimited in quotes or anything like that
Thanks

**Comment by jazanne** [comment]
@kostyay you can add the `kebabcase` alias to your configuration to find these references

```yaml
aliases:
  - type: kebabcase
```

More information available here: https://github.com/launchdarkly/ld-find-code-refs/blob/main/docs/ALIASES.md#flag-keys-transposed-to-common-casing-conventions

**Comment by kostyay** [comment]
Thanks worked

**Comment by kostyay** [comment]
So this didn't exactly work, in case anyone finds this thread this is the configuration that helped me:
```yaml
delimiters:
  disableDefaults: true
aliases:
  - type: kebabcase
 ```
