### ISSUE TITLE
Assets missing from 2.11.0 release, breaks Ubuntu install script

### ISSUE THREAD

**Issue by manbearwiz** [launchdarkly/ld-find-code-refs#378]
Previous releases all contain deb and rpm packages. The 2.11.0 release only contains the source archives. Is this intentional? 

https://github.com/launchdarkly/ld-find-code-refs/releases

**Comment by codyaray** [comment]
This is causing our builds to break too. Please fix 🙏

**Comment by jazanne** [comment]
Thank you for notifying us, we'll look into fixing this as soon as possible

**Comment by jazanne** [comment]
@manbearwiz @codyaray The assets have been added to the release. Please let me know if you have additional issues!
