### ISSUE TITLE
Release asset ld-find-code-refs_2.11.6_linux_amd64.tar.gz is being flagged by windows defender as having a virus

### ISSUE THREAD

**Issue by dfordthreecolts** [launchdarkly/ld-find-code-refs#427]
Our scanning scripts stopped working with this latest release and I discovered that Windows Defender is flagging it for a virus.

**Comment by jazanne** [comment]
@dfordthreecolts I'm sorry for the inconvenience.

I just released v2.11.7 of the application that has some security fixes in the docker alpine image. If you still have trouble with the new version, would if be possible for you to share some of the output from windows defender so we can better understand the issue?
