### ISSUE TITLE
Can't parse branch name

### ISSUE THREAD

**Issue by cparsonsdesign** [launchdarkly/ld-find-code-refs#85]
While trying to setup ld-find-code-refs I keep getting this error:

> INFO: 2019/07/16 10:42:56 command.go:191: absolute directory path: /opt/jenkins/LaunchDarkly/nodedemo/LD_Node_Test
> ERROR: 2019/07/16 10:42:56 coderefs.go:66: error parsing git branch name: Unknown option: -C
> usage: git [--version] [--help] [-c name=value]
>            [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
>            [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
>            [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
>            <command> [<args>]

I do not have -C anywhere in my command or in my branch name. 
I have verified that the dir is a git repo, 
I have explcitly told the repo to go to the master branch and I've tried the development branch.

I'm running "Red Hat Enterprise Linux Server 7.6 (Maipo)"

**Comment by atrakh** [comment]
Hi @cparsonsdesign,

Thanks for reporting this. This looks like an error from using an older version of git not currently supported by ld-find-code-refs. We've tested with git 2.21.0, but [git docs indicate](https://git-scm.com/docs/git/1.8.5) that this particular error would be resolved with a version >= 1.8.5.

Looks like Red Hat ships with git 1.8.4-- can you confirm that by running `git --version` in your command line? If this is the case, installing a newer version of git should resolve this issue. Please try that and let me know how it goes!

**Comment by cparsonsdesign** [comment]
I got the git upgraded and everything seems to be working now. Thank you guys for the quick response!

**Comment by atrakh** [comment]
Good to hear everything is working now! 

Going to close this issue now, but please don't hesitate to reach out to us again if you have any more questions.
