### ISSUE TITLE
Github Actions fails to resolve branch name

### ISSUE THREAD

**Issue by HoughIO** [launchdarkly/ld-find-code-refs#88]
Hey y'all!

I thought I would xpost this issue I filed with the Github Action: https://github.com/launchdarkly/find-code-references/issues/1

It seems that github's CICD pipeline uses a git ref to the pull request that triggered the event type. For instance from the [official action to clone your codebase](https://github.com/actions/checkout) I get the following output after cloning:

```BASH
git checkout --progress --force 37b3fff27de6b1487c19c54c57d9ecfea69dde03
 Note: checking out '37b3fff27de6b1487c19c54c57d9ecfea69dde03'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

```

Which causes an error in the LD action here:
```BASH
INFO: 2019/08/12 17:09:12 github-actions.go:24: Setting GitHub action env vars
INFO: 2019/08/12 17:09:12 github-actions.go:60: starting repo parsing program with options:
 map[defaultBranch:master repoUrl:https://github.com/ORG/REPO delimiters: exclude: baseUri: debug:false repoType:github repoName:REPO dir:/github/workspace updateSequenceId:1565629698000 accessToken: projKey:KEY contextLines:2]
INFO: 2019/08/12 17:09:12 command.go:191: absolute directory path: /github/workspace
ERROR: 2019/08/12 17:09:12 coderefs.go:66: error parsing git branch name: git repo at /github/workspace must be checked out to a valid branch
##[error]Docker run failed with exit code 1
```

After I filed that issue, I noticed that the codebase is in this repo, and found the reference here:
https://github.com/launchdarkly/ld-find-code-refs/blob/master/internal/command/command.go#L53

**Comment by vlymar** [comment]
Cross posting my response - https://github.com/launchdarkly/find-code-references/issues/1#issuecomment-520559774

**Comment by vlymar** [comment]
The issue local to this repo is fixed with https://github.com/launchdarkly/ld-find-code-refs/releases/tag/1.2.0. Please track https://github.com/launchdarkly/find-code-reference for the update to the action itself.

Thanks!
