### ISSUE TITLE
consider rg as an alternative to ag

### ISSUE THREAD

**Issue by softprops** [launchdarkly/ld-find-code-refs#90]
`rg` (ripgrep) is a popular alternative to `ag` and is about [5 times faster](https://github.com/BurntSushi/ripgrep#quick-examples-comparing-tools)  and is [widely available in most package systems](https://github.com/BurntSushi/ripgrep#installation)

I've found this a much more performant tool for searching through large repositories.

**Comment by cuzzasoft** [comment]
It looks like this was considered in https://github.com/launchdarkly/ld-find-code-refs/pull/81 but apparently abandoned?

**Comment by atrakh** [comment]
Hi all,

Thanks for showing interest in this functionality. @cuzzasoft is correct, we did explore adding support for ripgrep at one point. We decided against this decision to avoid adding additional complexity to configuration, as well as the additional risk of breaking existing functionality when using ripgrep (rg and ag output are slightly different and would require conditional logic).

Right now, we don't have any plans to add ripgrep support. If there are significant performance concerns, we may consider alternatives for search.

Have you been experiencing performance issues when scanning a larger repository? If you haven't already, I'd recommend setting up ignore rules to not scan files/directories that do not contain feature flags: https://github.com/launchdarkly/ld-find-code-refs#ignoring-files-and-directories.

**Comment by atrakh** [comment]
As of [2.0.0](https://github.com/launchdarkly/ld-find-code-refs/releases/tag/2.0.0), ld-find-code-refs uses a native search implementation without requiring a 3rd party dependency.

This implementation should have comparable, if not faster, performance for most cases.
