### ISSUE TITLE
Unable to run against larger repo

### ISSUE THREAD

**Issue by cuzzasoft** [launchdarkly/ld-find-code-refs#91]
I'm getting the below when running this against a larger repo:

```
docker run --rm -v /repo:/repo launchdarkly/ld-find-code-refs -dir="/repo" -repoName="frontend" -projKey="cats" -accessToken="${LD_AUTH}"

ld-find-code-refs version 1.2.0
INFO: 2019/09/03 00:12:54 command.go:199: absolute directory path: /repo
INFO: 2019/09/03 00:12:54 command.go:56: git branch: master
INFO: 2019/09/03 00:13:10 coderefs.go:215: finding code references with delimiters: ["'`]
ERROR: 2019/09/03 00:13:10 coderefs.go:130: error searching for flag key references: ERR: Bad regex! pcre_compile() failed at position 108921: regular expression is too large
If you meant to search for a literal string, run ag with -Q
```

Happens with both Docker image and also running it on Mac local machine. We have around 2k flags in the project I'm running it against.

Is there any way we can increase the regex limit, or paginate the execution of the app?

**Comment by cuzzasoft** [comment]
I 'fixed' this with the below:

```
diff --git a/.gitignore b/.gitignore
index e5fc37e..18cd1c2 100644
--- a/.gitignore
+++ b/.gitignore
@@ -6,3 +6,4 @@ build/package/bitbucket-pipelines/ld-find-code-refs-bitbucket-pipeline
 build/package/cmd/ld-find-code-refs
 /dist/
 /bin/
+.idea/
diff --git a/pkg/coderefs/coderefs.go b/pkg/coderefs/coderefs.go
index 9f49c19..f794045 100644
--- a/pkg/coderefs/coderefs.go
+++ b/pkg/coderefs/coderefs.go
@@ -213,12 +213,26 @@ func getFlags(ldApi ld.ApiClient) ([]string, error) {
 func (b *branch) findReferences(cmd command.Client, flags []string, ctxLines int, exclude *regexp.Regexp) (grepResultLines, error) {
 	delims := o.Delimiters.Value()
 	log.Info.Printf("finding code references with delimiters: %s", delims.String())
-	grepResult, err := cmd.SearchForFlags(flags, ctxLines, delims)
-	if err != nil {
-		return grepResultLines{}, err
+
+	var pageSize = 50
+	var grepResults [][]string
+	log.Info.Printf("paginating %d flags with a pagesize of %d", len(flags), pageSize)
+	for from := 0; from < len(flags); from += pageSize {
+		to := from + pageSize
+		if to > len(flags) {
+			to = len(flags)
+		}
+
+		log.Info.Printf("grepping for flags in group: [%d, %d]", from, to)
+		grepResult, err := cmd.SearchForFlags(flags[from:to], ctxLines, delims)
+		if err != nil {
+			return grepResultLines{}, err
+		}
+
+		grepResults = append(grepResults, grepResult...)
 	}
 
-	return generateReferencesFromGrep(flags, grepResult, ctxLines, exclude), nil
+	return generateReferencesFromGrep(flags, grepResults, ctxLines, exclude), nil
 }
 
 func generateReferencesFromGrep(flags []string, grepResult [][]string, ctxLines int, exclude *regexp.Regexp) []grepResultLine {

```

Would be happy to put in a PR but getting permission denied.

**Comment by atrakh** [comment]
Hi @cuzzasoft,

Thanks for reporting this issue. It's clear now that we need a way to search for references in projects with a very large number of flags, without `ld-find-code-refs` breaking.

The code above does work around the process failure, but is [not compatible](https://github.com/launchdarkly/ld-find-code-refs/blob/f68e960d80fc6595ac93eeba539deffd7820a3c1/pkg/coderefs/coderefs.go#L313) with the code reference processing algorithm applied to search results later, which could result in some code references being lost. So, we'll need to make some additional changes to resolve this issue.

If you'd like to make a pull request with your code for us to base changes off of, you can do so by forking this repository, and then following the instructions here: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork. In either case, I'll follow up again once we have an update on this.

**Comment by cuzzasoft** [comment]
Awesome mate, thank you for letting me know. I tried to put some sorting work in on that PR, but w/o knowing what y'all do I am a bit limited with the time I have available to get it going. I hope it kind of covers it

Appreciate the really fast response time too :)

**Comment by cuzzasoft** [comment]
Hey @atrakh with https://github.com/launchdarkly/ld-find-code-refs/pull/94 merged, do you have any rough ideas when the version will be released? I'd love to get it onto our build pipeline running automatically

Thanks :)

**Comment by atrakh** [comment]
Hi @cuzzasoft, thanks for following up. We're excited to get your team up and running with coderefs.

We're doing the last bit of QA on [rc-1.3.0](https://github.com/launchdarkly/ld-find-code-refs/tree/rc-1.3.0) before releasing. Barring any complications, we'll have the release out by Monday morning.

**Comment by atrakh** [comment]
Got to this sooner than I thought I would- [1.3.0](https://github.com/launchdarkly/ld-find-code-refs/releases) has now been released :)

Closing this issue now, but please do reach out again if you have any questions. Thanks again!
