### ISSUE TITLE
unable to retrieve branch list from remote

### ISSUE THREAD

**Issue by garthk** [launchdarkly/ld-find-code-refs#98]
I gave `-branch`. Why is `ld-find-code-refs` trying to retrieve the branch list from the remote? 

~Why are you trying to delete branches ("skipping branch deletion")? If that's optional, why do you then crash out as if it's fatal?~ Update: [it is deleting branch entries at LaunchDarkly](https://github.com/launchdarkly/ld-find-code-refs/blob/f68e960d80fc6595ac93eeba539deffd7820a3c1/pkg/coderefs/coderefs.go#L152). It's only scary because the log entries intermingle with actual git operations.

```
$ docker run --rm -w $PWD -v $PWD:$PWD launchdarkly/ld-find-code-refs -accessToken=$LAUNCH_DARKLY_ACCESS_TOKEN -branch $CI_GIT_BRANCH -contextLines=2 -dir=. -projKey=default -repoName=reponame -repoType=github -repoUrl=https://github.com/example.com/reponame -debug
ld-find-code-refs version 1.2.0
INFO: 2019/09/19 05:37:12 command.go:199: absolute directory path: /home/reponame
INFO: 2019/09/19 05:37:12 command.go:56: git branch: feature/report-list-view
DEBUG: 2019/09/19 05:37:12 command.go:97: identified head sha: a73bd4cce8b3480148205d4c72a13eefd9fefe54
DEBUG: 2019/09/19 05:37:12 client.go:344: [DEBUG] GET https://app.launchdarkly.com/api/v2/code-refs/repositories/reponame
DEBUG: 2019/09/19 05:37:12 client.go:344: [DEBUG] PATCH https://app.launchdarkly.com/api/v2/code-refs/repositories/reponame
INFO: 2019/09/19 05:37:13 coderefs.go:215: finding code references with delimiters: ["'`]
INFO: 2019/09/19 05:37:13 coderefs.go:135: sending 0 code references across 1 flags and 0 files to LaunchDarkly for project: default
     FLAG     | # REFERENCES  
+-------------+--------------+
  Other flags |            0  
DEBUG: 2019/09/19 05:37:13 client.go:344: [DEBUG] PUT https://app.launchdarkly.com/api/v2/code-refs/repositories/reponame/branches/feature%2Freport-list-view
WARNING: 2019/09/19 05:37:13 coderefs.go:152: unable to retrieve branch list from remote, skipping branch deletion: Host key verification failed.
fatal: Could not read from remote repository.
```

**Comment by brandon-sling** [comment]
Had this nightmare for a second too, until I realized that if I thought logically that is what I would want it to do, so the text probably meant that. Maybe need to clean up the language in those logging statements to better reflect what is happening. Also the README.MD

**Comment by atrakh** [comment]
Hi, @garthk, thanks for bringing this to our attention.

As you've discovered, `ld-find-code-refs` attempts to prune code reference data in LD for branches that have already been deleted from the remote, but still have existing code references stored in LD. `ld-find-code-refs` will never perform any mutative action on your git repository.

However, I can see how that warning log can be misleading-- we'll clean up the language here per @brandon-sling's suggestion.

**Comment by atrakh** [comment]
Updated logging in [1.3.0](https://github.com/launchdarkly/ld-find-code-refs/releases/tag/1.3.0). Thanks again everyone!
